<a href="https://colab.research.google.com/github/namita14/python/blob/master/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [29]:
import numpy as np
list1 = [21, 12 , 2 , 33 , 56]
list2 = [1, 5, 7, 9, 3]
print(list1)
print(list2)
arr1 = np.array(list1)
arr2 = np.array(list2)
print(arr1)
print(arr2)
print(np.concatenate((arr1, arr2)))
print(np.sort(arr1))
print(np.sort(arr2))

[21, 12, 2, 33, 56]
[1, 5, 7, 9, 3]
[21 12  2 33 56]
[1 5 7 9 3]
[21 12  2 33 56  1  5  7  9  3]
[ 2 12 21 33 56]
[1 3 5 7 9]


In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
type(x)
x.shape
x.dtype


dtype('int32')

In [ ]:
import numpy as np
a = np.arange(6)
a.ndim
c = np.reshape(a, (2,3))
c.ndim

In [13]:
## Horitzontal Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

## Vertical Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


In [15]:
import numpy as np
number_list = np.array([1, 1, 2, 3, 4, 4, 1])

(unique, counts) = np.unique(number_list, return_counts=True)
frequencies = np.asarray((unique, counts)).T

print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
